### PR TITLE
Fix authorized user validation bug

### PR DESCRIPTION
**Pull request by dmitryserbin**
This change fixes a bug in the `check_user` decorator, which causes an exception when the `GITHUB_USERS` variable is not present but an authorization header is specified in the request (e.g., when accessing a private organization).

The use case is when multiple users consume the service accessing private EMU organizations. I.e. they must provide authorization header, but we don't know all possible users upfront whitelist the logins.

- Updated `ghmirror/decorators/checks.py` with a fix.
- Added two more `tests/functional/test_api.py` tests.
- Updated `pyproject.toml` rule to allow 7 max-returns (please suggest better conditional logic in `check_user` if not happy).

**Current behaviour:**

```bash
export GITHUB_USERS=""

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer mytoken" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  http://localhost:8080/orgs/myorg/repos
```

```json
{
  "message": "Error reaching https://api.github.com: AttributeError"
}
```

**Expected behaviour:**

API response is returned.

### CODE REVIEW

**Comment by dmitryserbin** [comment]
Hi @rporres could you please review when you have a moment? Cheers

**Comment by dmitryserbin** [comment]
Thanks for spending time on this @hemslo!

My use case is when multiple users consume the service accessing private EMU organizations. I.e. they must provide authorization header, but we don't know all possible users upfront whitelist the logins.

I've made the changes you suggested, thanks for that. Also, max-returns is back to 6 now.

Let me know if there's anything else I can do.

**Comment by dmitryserbin** [comment]
Just fixed the tests, should be all good now @hemslo

**Review by hemslo — APPROVED** [review]
LGTM!

**Pull request merged**
