### PR TITLE
Turning the /stats endpoint into prometheus /metrics endpoint

### PR DESCRIPTION
**Pull request by apahim**
Example::

    # HELP process_virtual_memory_bytes Virtual memory size in bytes.
    # TYPE process_virtual_memory_bytes gauge
    process_virtual_memory_bytes 6.32803328e+08
    # HELP process_resident_memory_bytes Resident memory size in bytes.
    # TYPE process_resident_memory_bytes gauge
    process_resident_memory_bytes 3.6941824e+07
    # HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
    # TYPE process_start_time_seconds gauge
    process_start_time_seconds 1.58168813995e+09
    # HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
    # TYPE process_cpu_seconds_total counter
    process_cpu_seconds_total 9.69
    # HELP process_open_fds Number of open file descriptors.
    # TYPE process_open_fds gauge
    process_open_fds 9.0
    # HELP process_max_fds Maximum number of open file descriptors.
    # TYPE process_max_fds gauge
    process_max_fds 1024.0
    # HELP http_request_total total requests
    # TYPE http_request_total counter
    http_request_total 199.0
    # TYPE http_request_created gauge
    http_request_created 1.5816881418336885e+09
    # HELP request_latency_seconds Description of histogram
    # TYPE request_latency_seconds histogram
    request_latency_seconds_bucket{cache="MISS",le="0.005",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.01",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.025",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.05",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.075",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.1",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.25",method="GET",status="404"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.5",method="GET",status="404"} 51.0
    request_latency_seconds_bucket{cache="MISS",le="0.75",method="GET",status="404"} 58.0
    request_latency_seconds_bucket{cache="MISS",le="1.0",method="GET",status="404"} 60.0
    request_latency_seconds_bucket{cache="MISS",le="2.5",method="GET",status="404"} 60.0
    request_latency_seconds_bucket{cache="MISS",le="5.0",method="GET",status="404"} 60.0
    request_latency_seconds_bucket{cache="MISS",le="7.5",method="GET",status="404"} 60.0
    request_latency_seconds_bucket{cache="MISS",le="10.0",method="GET",status="404"} 60.0
    request_latency_seconds_bucket{cache="MISS",le="+Inf",method="GET",status="404"} 60.0
    request_latency_seconds_count{cache="MISS",method="GET",status="404"} 60.0
    request_latency_seconds_sum{cache="MISS",method="GET",status="404"} 29.620453357696533
    request_latency_seconds_bucket{cache="MISS",le="0.005",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.01",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.025",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.05",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.075",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.1",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.25",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.5",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.75",method="GET",status="200"} 6.0
    request_latency_seconds_bucket{cache="MISS",le="1.0",method="GET",status="200"} 7.0
    request_latency_seconds_bucket{cache="MISS",le="2.5",method="GET",status="200"} 7.0
    request_latency_seconds_bucket{cache="MISS",le="5.0",method="GET",status="200"} 7.0
    request_latency_seconds_bucket{cache="MISS",le="7.5",method="GET",status="200"} 7.0
    request_latency_seconds_bucket{cache="MISS",le="10.0",method="GET",status="200"} 7.0
    request_latency_seconds_bucket{cache="MISS",le="+Inf",method="GET",status="200"} 7.0
    request_latency_seconds_count{cache="MISS",method="GET",status="200"} 7.0
    request_latency_seconds_sum{cache="MISS",method="GET",status="200"} 4.457277536392212
    request_latency_seconds_bucket{cache="HIT",le="0.005",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.01",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.025",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.05",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.075",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.1",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.25",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.5",method="GET",status="200"} 0.0
    request_latency_seconds_bucket{cache="HIT",le="0.75",method="GET",status="200"} 124.0
    request_latency_seconds_bucket{cache="HIT",le="1.0",method="GET",status="200"} 130.0
    request_latency_seconds_bucket{cache="HIT",le="2.5",method="GET",status="200"} 130.0
    request_latency_seconds_bucket{cache="HIT",le="5.0",method="GET",status="200"} 130.0
    request_latency_seconds_bucket{cache="HIT",le="7.5",method="GET",status="200"} 130.0
    request_latency_seconds_bucket{cache="HIT",le="10.0",method="GET",status="200"} 130.0
    request_latency_seconds_bucket{cache="HIT",le="+Inf",method="GET",status="200"} 130.0
    request_latency_seconds_count{cache="HIT",method="GET",status="200"} 130.0
    request_latency_seconds_sum{cache="HIT",method="GET",status="200"} 76.75304985046387
    request_latency_seconds_bucket{cache="MISS",le="0.005",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.01",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.025",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.05",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.075",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.1",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.25",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.5",method="PATCH",status="200"} 0.0
    request_latency_seconds_bucket{cache="MISS",le="0.75",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="1.0",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="2.5",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="5.0",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="7.5",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="10.0",method="PATCH",status="200"} 2.0
    request_latency_seconds_bucket{cache="MISS",le="+Inf",method="PATCH",status="200"} 2.0
    request_latency_seconds_count{cache="MISS",method="PATCH",status="200"} 2.0
    request_latency_seconds_sum{cache="MISS",method="PATCH",status="200"} 1.2275147438049316
    # TYPE request_latency_seconds_created gauge
    request_latency_seconds_created{cache="MISS",method="GET",status="404"} 1.5816881418340204e+09
    request_latency_seconds_created{cache="MISS",method="GET",status="200"} 1.5816881418628085e+09
    request_latency_seconds_created{cache="HIT",method="GET",status="200"} 1.5816881427032213e+09
    request_latency_seconds_created{cache="MISS",method="PATCH",status="200"} 1.5816882104669194e+09

### CODE REVIEW

**Comment by apahim** [comment]
@rporres @jfchevrette

**Comment by rporres** [comment]
It looks great to have a prometheus endpoint \o/:

* If I'm not mistaken this is going to work fine as we only have one process running, isn't it? You have to do further work if you want the metrics to be shared between processes
* What are those `cache_hits_created` and `cache_misses_created` metrics? An old name?
* Since this is a server, it would also great to have requests, latencies, etc. As a super cool thing it would be interesting to know how much of the time of a request comes from github and how much from the server. This may help us in the future to determine if we're having any issue with the server, an external cache, etc...

**Comment by jfchevrette** [comment]
This is great! Well done!

If we run more than one replica, we'll have to craft promql queries that will sum the metrics aross the pods. This is super easy to do and a common pattern. 

As @rporres pointed out, it would be very useful to expose the http server's own metrics, such as http requests, latency, etc... This seem adequate: https://github.com/rycus86/prometheus_flask_exporter

**Comment by rporres** [comment]
> If we run more than one replica, we'll have to craft promql queries that will sum the metrics aross the pods. This is super easy to do and a common pattern.

I was thinking on two workers defined in https://github.com/app-sre/github-mirror/blob/master/Dockerfile. As this is going to be run in k8s and we can scale it via pod scaling, maybe it's just a matter to add a note saying that prometheus only supports one worker and avoid any further work.

**Comment by apahim** [comment]
Yes.. I already want to limit the number of (gunicorn) workers because that will give us separate caching instances. So, let's think of this as one python session per container, no multiprocessing. Multiple container replicas might still be the case though.

**Comment by apahim** [comment]
**If I'm not mistaken this is going to work fine as we only have one process running, isn't it? You have to do further work if you want the metrics to be shared between processes**

I already wanted to limit the number of python sessions to one due to the cache sharing. Now we have yet another reason.

**What are those cache_hits_created and cache_misses_created metrics? An old name?**
They are auto-included by the prometheus client when adding a Counter. Not sure how useful they are.

**Since this is a server, it would also great to have requests, latencies, etc. As a super cool thing it would be interesting to know how much of the time of a request comes from github and how much from the server.**

+1

**As @rporres pointed out, it would be very useful to expose the http server's own metrics, such as http requests, latency, etc... This seem adequate: https://github.com/rycus86/prometheus_flask_exporter**

Yep, +1

**I was thinking on two workers defined in https://github.com/app-sre/github-mirror/blob/master/Dockerfile. As this is going to be run in k8s and we can scale it via pod scaling, maybe it's just a matter to add a note saying that prometheus only supports one worker and avoid any further work.**

Agreed... let's just avoid having multiple workers there.

**Comment by aditya-konarde** [comment]
Joining the party super late, sorry. Overall this looks good to me and thanks for addressing the comments by @rporres and @jfchevrette which were spot on :)

**Pull request merged**
